### ISSUE TITLE
Duplicate volunteer records

### ISSUE THREAD

**Issue by rlp612** [rlp612/MUBS-Webpage#6]
The MyCampaign_data_scrape table now has duplicate entries for every volunteer.  Need to resolve what caused this.  Perhaps the table wasn't wiped during the last MyCampaign data scrape.

Recommended approach:  wipe the table and scrape MyCampaign again to replace

**Comment by RZachLamberty** [comment]
the original problem was deciding to do a REPLACE (instead of wipe and insert) on records with a unique increment column (scrapeID). When the scraper looked to REPLACE, all records were different from their previous scrape by that increment id, so they were treated as new and inserted.

To solve, I
- dropped the dupes (easy to find -- they had a NULL scrapeDate because they were from the very first run)
- dropped the scrapeID column.

No dupes for VANID now.
