### ISSUE TITLE
speed up initial table load

### ISSUE THREAD

**Issue by RZachLamberty** [rlp612/MUBS-Webpage#8]
maybe cache it with timeout

**Comment by rlp612** [comment]
I built a stored procedure called Create_page_view() which creates a table called Page_View that looks exactly like the results from the previous MUBS_Page_View stored view.  I then changed the MUBS_Page_View stored view to Select \* from Page_View.  Since the heavy joining is done by the stored procedure, the stored view is now very fast.  However, this means that the data will get stale unless we call the Create_page_view() procedure at the end of every new data scrape.  So, I'll open a new ticket to add that step to the scraping process.
